coverage:
  status:
    patch:
      default:
        target: 80%
        informational: true
    project:
      default:
        informational: true

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: true
